// Generated by generate/std

package main

var pkgs = map[string][]string{
	"archive/tar": {
		"numBytesReader",
	},
	"archive/zip": {
		"Compressor",
		"Decompressor",
	},
	"bufio": {
		"SplitFunc",
	},
	"compress/flate": {
		"Reader",
		"Resetter",
	},
	"compress/zlib": {
		"Resetter",
	},
	"container/heap": {
		"Interface",
	},
	"crypto": {
		"Decrypter",
		"Signer",
		"SignerOpts",
	},
	"crypto/cipher": {
		"AEAD",
		"Block",
		"BlockMode",
		"Stream",
	},
	"crypto/elliptic": {
		"Curve",
	},
	"crypto/tls": {
		"ClientSessionCache",
		"macFunction",
	},
	"database/sql": {
		"Result",
		"Scanner",
		"finalCloser",
	},
	"database/sql/driver": {
		"ColumnConverter",
		"Conn",
		"Driver",
		"Execer",
		"Queryer",
		"Result",
		"Rows",
		"Stmt",
		"Tx",
		"ValueConverter",
		"Valuer",
	},
	"debug/dwarf": {
		"Type",
		"dataFormat",
		"typeReader",
	},
	"debug/macho": {
		"Load",
	},
	"encoding": {
		"BinaryMarshaler",
		"BinaryUnmarshaler",
		"TextMarshaler",
		"TextUnmarshaler",
	},
	"encoding/binary": {
		"ByteOrder",
	},
	"encoding/gob": {
		"GobDecoder",
		"GobEncoder",
		"decHelper",
		"decOp",
		"encHelper",
		"encOp",
		"gobType",
	},
	"encoding/json": {
		"Marshaler",
		"Unmarshaler",
	},
	"encoding/xml": {
		"Marshaler",
		"MarshalerAttr",
		"Unmarshaler",
		"UnmarshalerAttr",
	},
	"flag": {
		"Getter",
		"Value",
	},
	"fmt": {
		"Formatter",
		"GoStringer",
		"ScanState",
		"Scanner",
		"State",
		"Stringer",
	},
	"go/ast": {
		"Decl",
		"Expr",
		"FieldFilter",
		"Filter",
		"Importer",
		"Node",
		"Spec",
		"Stmt",
		"Visitor",
	},
	"go/constant": {
		"Value",
	},
	"go/doc": {
		"Filter",
	},
	"go/importer": {
		"Lookup",
	},
	"go/scanner": {
		"ErrorHandler",
	},
	"go/types": {
		"Importer",
		"Object",
		"Qualifier",
		"Sizes",
		"Type",
		"getter",
	},
	"hash": {
		"Hash",
		"Hash32",
		"Hash64",
	},
	"image": {
		"Image",
		"PalettedImage",
	},
	"image/color": {
		"Color",
		"Model",
	},
	"image/draw": {
		"Drawer",
		"Image",
		"Quantizer",
	},
	"image/jpeg": {
		"Reader",
	},
	"io": {
		"ByteReader",
		"ByteScanner",
		"ByteWriter",
		"Closer",
		"ReadCloser",
		"ReadSeeker",
		"ReadWriteCloser",
		"ReadWriteSeeker",
		"ReadWriter",
		"Reader",
		"ReaderAt",
		"ReaderFrom",
		"RuneReader",
		"RuneScanner",
		"Seeker",
		"WriteCloser",
		"WriteSeeker",
		"Writer",
		"WriterAt",
		"WriterTo",
	},
	"log/syslog": {
		"serverConn",
	},
	"math/rand": {
		"Source",
	},
	"mime/multipart": {
		"File",
	},
	"net": {
		"Addr",
		"Conn",
		"Error",
		"Listener",
		"PacketConn",
		"dnsConn",
		"dnsRR",
		"sockaddr",
	},
	"net/http": {
		"CloseNotifier",
		"CookieJar",
		"File",
		"FileSystem",
		"Flusher",
		"Handler",
		"HandlerFunc",
		"Hijacker",
		"ResponseWriter",
		"RoundTripper",
	},
	"net/http/cookiejar": {
		"PublicSuffixList",
	},
	"net/rpc": {
		"ClientCodec",
		"ServerCodec",
	},
	"net/smtp": {
		"Auth",
	},
	"os": {
		"FileInfo",
		"Signal",
	},
	"path/filepath": {
		"WalkFunc",
	},
	"reflect": {
		"Type",
	},
	"regexp": {
		"input",
	},
	"runtime": {
		"Error",
	},
	"sort": {
		"Interface",
	},
	"strings": {
		"replacer",
	},
	"sync": {
		"Locker",
	},
	"syscall": {
		"Sockaddr",
	},
	"testing": {
		"TB",
	},
	"testing/quick": {
		"Generator",
	},
	"text/template/parse": {
		"Node",
		"stateFn",
	},
}
