// Generated by generate/std

package main

type pkgNames struct {
	path  string
	names []string
}

var pkgs = [...]pkgNames{
	{
		path: "",
		names: []string{
			"error",
		},
	},
	{
		path: "io",
		names: []string{
			"ByteReader",
			"ByteScanner",
			"ByteWriter",
			"Closer",
			"ReadCloser",
			"ReadSeeker",
			"ReadWriteCloser",
			"ReadWriteSeeker",
			"ReadWriter",
			"Reader",
			"ReaderAt",
			"ReaderFrom",
			"RuneReader",
			"RuneScanner",
			"Seeker",
			"WriteCloser",
			"WriteSeeker",
			"Writer",
			"WriterAt",
			"WriterTo",
		},
	},
	{
		path: "os",
		names: []string{
			"FileInfo",
			"Signal",
		},
	},
	{
		path: "fmt",
		names: []string{
			"Formatter",
			"GoStringer",
			"ScanState",
			"Scanner",
			"State",
			"Stringer",
		},
	},
	{
		path:  "log",
		names: []string{},
	},
	{
		path: "net",
		names: []string{
			"Addr",
			"Conn",
			"Error",
			"Listener",
			"PacketConn",
			"dnsConn",
			"dnsRR",
			"sockaddr",
		},
	},
	{
		path: "flag",
		names: []string{
			"Getter",
			"Value",
		},
	},
	{
		path: "hash",
		names: []string{
			"Hash",
			"Hash32",
			"Hash64",
		},
	},
	{
		path:  "html",
		names: []string{},
	},
	{
		path:  "math",
		names: []string{},
	},
	{
		path:  "mime",
		names: []string{},
	},
	{
		path:  "path",
		names: []string{},
	},
	{
		path: "sort",
		names: []string{
			"Interface",
		},
	},
	{
		path: "sync",
		names: []string{
			"Locker",
		},
	},
	{
		path:  "time",
		names: []string{},
	},
	{
		path: "bufio",
		names: []string{
			"SplitFunc",
		},
	},
	{
		path:  "bytes",
		names: []string{},
	},
	{
		path: "image",
		names: []string{
			"Image",
			"PalettedImage",
		},
	},
	{
		path: "crypto",
		names: []string{
			"Decrypter",
			"Signer",
			"SignerOpts",
		},
	},
	{
		path:  "errors",
		names: []string{},
	},
	{
		path: "expvar",
		names: []string{
			"Func",
			"Var",
		},
	},
	{
		path: "go/ast",
		names: []string{
			"Decl",
			"Expr",
			"FieldFilter",
			"Filter",
			"Importer",
			"Node",
			"Spec",
			"Stmt",
			"Visitor",
		},
	},
	{
		path: "go/doc",
		names: []string{
			"Filter",
		},
	},
	{
		path: "regexp",
		names: []string{
			"input",
		},
	},
	{
		path: "net/rpc",
		names: []string{
			"ClientCodec",
			"ServerCodec",
		},
	},
	{
		path:  "net/url",
		names: []string{},
	},
	{
		path:  "os/exec",
		names: []string{},
	},
	{
		path:  "os/user",
		names: []string{},
	},
	{
		path: "reflect",
		names: []string{
			"Type",
		},
	},
	{
		path: "runtime",
		names: []string{
			"Error",
		},
	},
	{
		path:  "strconv",
		names: []string{},
	},
	{
		path: "strings",
		names: []string{
			"replacer",
		},
	},
	{
		path: "syscall",
		names: []string{
			"Sockaddr",
		},
	},
	{
		path: "testing",
		names: []string{
			"TB",
		},
	},
	{
		path:  "unicode",
		names: []string{},
	},
	{
		path:  "debug/pe",
		names: []string{},
	},
	{
		path: "encoding",
		names: []string{
			"BinaryMarshaler",
			"BinaryUnmarshaler",
			"TextMarshaler",
			"TextUnmarshaler",
		},
	},
	{
		path:  "go/build",
		names: []string{},
	},
	{
		path:  "go/token",
		names: []string{},
	},
	{
		path: "go/types",
		names: []string{
			"Importer",
			"Object",
			"Qualifier",
			"Sizes",
			"Type",
			"getter",
		},
	},
	{
		path:  "hash/fnv",
		names: []string{},
	},
	{
		path:  "math/big",
		names: []string{},
	},
	{
		path: "net/http",
		names: []string{
			"CloseNotifier",
			"CookieJar",
			"File",
			"FileSystem",
			"Flusher",
			"Handler",
			"HandlerFunc",
			"Hijacker",
			"ResponseWriter",
			"RoundTripper",
		},
	},
	{
		path:  "net/mail",
		names: []string{},
	},
	{
		path: "net/smtp",
		names: []string{
			"Auth",
		},
	},
	{
		path:  "debug/elf",
		names: []string{},
	},
	{
		path:  "go/format",
		names: []string{},
	},
	{
		path:  "go/parser",
		names: []string{},
	},
	{
		path:  "image/gif",
		names: []string{},
	},
	{
		path:  "image/png",
		names: []string{},
	},
	{
		path:  "io/ioutil",
		names: []string{},
	},
	{
		path: "math/rand",
		names: []string{
			"Source",
		},
	},
	{
		path:  "os/signal",
		names: []string{},
	},
	{
		path:  "crypto/aes",
		names: []string{},
	},
	{
		path:  "crypto/des",
		names: []string{},
	},
	{
		path:  "crypto/dsa",
		names: []string{},
	},
	{
		path:  "crypto/md5",
		names: []string{},
	},
	{
		path:  "crypto/rc4",
		names: []string{},
	},
	{
		path:  "crypto/rsa",
		names: []string{},
	},
	{
		path: "crypto/tls",
		names: []string{
			"ClientSessionCache",
			"macFunction",
		},
	},
	{
		path:  "go/printer",
		names: []string{},
	},
	{
		path: "go/scanner",
		names: []string{
			"ErrorHandler",
		},
	},
	{
		path:  "hash/crc32",
		names: []string{},
	},
	{
		path:  "hash/crc64",
		names: []string{},
	},
	{
		path: "image/draw",
		names: []string{
			"Drawer",
			"Image",
			"Quantizer",
		},
	},
	{
		path: "image/jpeg",
		names: []string{
			"Reader",
		},
	},
	{
		path: "log/syslog",
		names: []string{
			"serverConn",
		},
	},
	{
		path:  "math/cmplx",
		names: []string{},
	},
	{
		path: "archive/tar",
		names: []string{
			"numBytesReader",
		},
	},
	{
		path: "archive/zip",
		names: []string{
			"Compressor",
			"Decompressor",
		},
	},
	{
		path:  "crypto/hmac",
		names: []string{},
	},
	{
		path:  "crypto/rand",
		names: []string{},
	},
	{
		path:  "crypto/sha1",
		names: []string{},
	},
	{
		path:  "crypto/x509",
		names: []string{},
	},
	{
		path: "debug/dwarf",
		names: []string{
			"Type",
			"dataFormat",
			"typeReader",
		},
	},
	{
		path:  "debug/gosym",
		names: []string{},
	},
	{
		path: "debug/macho",
		names: []string{
			"Load",
		},
	},
	{
		path: "go/constant",
		names: []string{
			"Value",
		},
	},
	{
		path: "go/importer",
		names: []string{
			"Lookup",
		},
	},
	{
		path: "image/color",
		names: []string{
			"Color",
			"Model",
		},
	},
	{
		path:  "runtime/cgo",
		names: []string{},
	},
	{
		path:  "sync/atomic",
		names: []string{},
	},
	{
		path:  "compress/lzw",
		names: []string{},
	},
	{
		path:  "crypto/ecdsa",
		names: []string{},
	},
	{
		path: "database/sql",
		names: []string{
			"Result",
			"Scanner",
			"finalCloser",
		},
	},
	{
		path:  "encoding/csv",
		names: []string{},
	},
	{
		path: "encoding/gob",
		names: []string{
			"GobDecoder",
			"GobEncoder",
			"decHelper",
			"decOp",
			"encHelper",
			"encOp",
			"gobType",
		},
	},
	{
		path:  "encoding/hex",
		names: []string{},
	},
	{
		path:  "encoding/pem",
		names: []string{},
	},
	{
		path: "encoding/xml",
		names: []string{
			"Marshaler",
			"MarshalerAttr",
			"Unmarshaler",
			"UnmarshalerAttr",
		},
	},
	{
		path:  "hash/adler32",
		names: []string{},
	},
	{
		path:  "net/http/cgi",
		names: []string{},
	},
	{
		path:  "runtime/race",
		names: []string{},
	},
	{
		path:  "text/scanner",
		names: []string{},
	},
	{
		path:  "unicode/utf8",
		names: []string{},
	},
	{
		path:  "compress/gzip",
		names: []string{},
	},
	{
		path: "compress/zlib",
		names: []string{
			"Resetter",
		},
	},
	{
		path: "crypto/cipher",
		names: []string{
			"AEAD",
			"Block",
			"BlockMode",
			"Stream",
		},
	},
	{
		path:  "crypto/sha256",
		names: []string{},
	},
	{
		path:  "crypto/sha512",
		names: []string{},
	},
	{
		path:  "crypto/subtle",
		names: []string{},
	},
	{
		path:  "encoding/asn1",
		names: []string{},
	},
	{
		path: "encoding/json",
		names: []string{
			"Marshaler",
			"Unmarshaler",
		},
	},
	{
		path:  "html/template",
		names: []string{},
	},
	{
		path:  "net/http/fcgi",
		names: []string{},
	},
	{
		path:  "net/textproto",
		names: []string{},
	},
	{
		path: "path/filepath",
		names: []string{
			"WalkFunc",
		},
	},
	{
		path:  "regexp/syntax",
		names: []string{},
	},
	{
		path:  "runtime/debug",
		names: []string{},
	},
	{
		path:  "runtime/pprof",
		names: []string{},
	},
	{
		path:  "runtime/trace",
		names: []string{},
	},
	{
		path: "testing/quick",
		names: []string{
			"Generator",
		},
	},
	{
		path:  "text/template",
		names: []string{},
	},
	{
		path:  "unicode/utf16",
		names: []string{},
	},
	{
		path:  "compress/bzip2",
		names: []string{},
	},
	{
		path: "compress/flate",
		names: []string{
			"Reader",
			"Resetter",
		},
	},
	{
		path: "container/heap",
		names: []string{
			"Interface",
		},
	},
	{
		path:  "container/list",
		names: []string{},
	},
	{
		path:  "container/ring",
		names: []string{},
	},
	{
		path:  "debug/plan9obj",
		names: []string{},
	},
	{
		path: "mime/multipart",
		names: []string{
			"File",
		},
	},
	{
		path:  "net/http/pprof",
		names: []string{},
	},
	{
		path:  "testing/iotest",
		names: []string{},
	},
	{
		path:  "text/tabwriter",
		names: []string{},
	},
	{
		path: "crypto/elliptic",
		names: []string{
			"Curve",
		},
	},
	{
		path:  "encoding/base32",
		names: []string{},
	},
	{
		path:  "encoding/base64",
		names: []string{},
	},
	{
		path: "encoding/binary",
		names: []string{
			"ByteOrder",
		},
	},
	{
		path:  "net/rpc/jsonrpc",
		names: []string{},
	},
	{
		path:  "crypto/x509/pkix",
		names: []string{},
	},
	{
		path:  "encoding/ascii85",
		names: []string{},
	},
	{
		path:  "index/suffixarray",
		names: []string{},
	},
	{
		path:  "net/http/httptest",
		names: []string{},
	},
	{
		path:  "net/http/httputil",
		names: []string{},
	},
	{
		path: "net/http/cookiejar",
		names: []string{
			"PublicSuffixList",
		},
	},
	{
		path: "database/sql/driver",
		names: []string{
			"ColumnConverter",
			"Conn",
			"Driver",
			"Execer",
			"Queryer",
			"Result",
			"Rows",
			"Stmt",
			"Tx",
			"ValueConverter",
			"Valuer",
		},
	},
	{
		path:  "image/color/palette",
		names: []string{},
	},
	{
		path: "text/template/parse",
		names: []string{
			"Node",
			"stateFn",
		},
	},
	{
		path:  "mime/quotedprintable",
		names: []string{},
	},
}
